// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package solubris.marketmon.domain;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import solubris.marketmon.domain.EventType;
import solubris.marketmon.domain.EventTypeIntegrationTest;

privileged aspect EventTypeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EventTypeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EventTypeIntegrationTest: @Transactional;
    
    @Test
    public void EventTypeIntegrationTest.testCountEventTypes() {
        Assert.assertNotNull("Data on demand for 'EventType' failed to initialize correctly", dod.getRandomEventType());
        long count = EventType.countEventTypes();
        Assert.assertTrue("Counter for 'EventType' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void EventTypeIntegrationTest.testFindEventType() {
        EventType obj = dod.getRandomEventType();
        Assert.assertNotNull("Data on demand for 'EventType' failed to initialize correctly", obj);
        Long id = obj.getEventTypeId();
        Assert.assertNotNull("Data on demand for 'EventType' failed to provide an identifier", id);
        obj = EventType.findEventType(id);
        Assert.assertNotNull("Find method for 'EventType' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'EventType' returned the incorrect identifier", id, obj.getEventTypeId());
    }
    
    @Test
    public void EventTypeIntegrationTest.testFindAllEventTypes() {
        Assert.assertNotNull("Data on demand for 'EventType' failed to initialize correctly", dod.getRandomEventType());
        long count = EventType.countEventTypes();
        Assert.assertTrue("Too expensive to perform a find all test for 'EventType', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<EventType> result = EventType.findAllEventTypes();
        Assert.assertNotNull("Find all method for 'EventType' illegally returned null", result);
        Assert.assertTrue("Find all method for 'EventType' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void EventTypeIntegrationTest.testFindEventTypeEntries() {
        Assert.assertNotNull("Data on demand for 'EventType' failed to initialize correctly", dod.getRandomEventType());
        long count = EventType.countEventTypes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<EventType> result = EventType.findEventTypeEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'EventType' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'EventType' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void EventTypeIntegrationTest.testFlush() {
        EventType obj = dod.getRandomEventType();
        Assert.assertNotNull("Data on demand for 'EventType' failed to initialize correctly", obj);
        Long id = obj.getEventTypeId();
        Assert.assertNotNull("Data on demand for 'EventType' failed to provide an identifier", id);
        obj = EventType.findEventType(id);
        Assert.assertNotNull("Find method for 'EventType' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyEventType(obj);
        Short currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'EventType' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EventTypeIntegrationTest.testMergeUpdate() {
        EventType obj = dod.getRandomEventType();
        Assert.assertNotNull("Data on demand for 'EventType' failed to initialize correctly", obj);
        Long id = obj.getEventTypeId();
        Assert.assertNotNull("Data on demand for 'EventType' failed to provide an identifier", id);
        obj = EventType.findEventType(id);
        boolean modified =  dod.modifyEventType(obj);
        Short currentVersion = obj.getVersion();
        EventType merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getEventTypeId(), id);
        Assert.assertTrue("Version for 'EventType' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void EventTypeIntegrationTest.testRemove() {
        EventType obj = dod.getRandomEventType();
        Assert.assertNotNull("Data on demand for 'EventType' failed to initialize correctly", obj);
        Long id = obj.getEventTypeId();
        Assert.assertNotNull("Data on demand for 'EventType' failed to provide an identifier", id);
        obj = EventType.findEventType(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'EventType' with identifier '" + id + "'", EventType.findEventType(id));
    }
    
}
