// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package solubris.marketmon.domain;

import org.springframework.beans.factory.annotation.Configurable;
import solubris.marketmon.domain.PriceSizeForLay;

privileged aspect PriceSizeForLay_Roo_Configurable {
    
    declare @type: PriceSizeForLay: @Configurable;
    
}
