// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package solubris.marketmon.domain;

import javax.persistence.Entity;
import solubris.marketmon.domain.PriceSizeForLay;

privileged aspect PriceSizeForLay_Roo_Jpa_Entity {
    
    declare @type: PriceSizeForLay: @Entity;
    
}
